POST /api/v1/generate HTTP/1.1
HOST: localhost:8000
Content-type: application/json

{
    "nunet":"anonymous",
    "url":"https://www.eng.nu.ac.th",
    "ref_id":"6861",
    "secret":"EihAe6AZxe0XDPUbsdlFbLijiWJwxySXQmFdqO5xEAw=",
    "workcode":"ENV123/2568",
    "back_color":"Violet",
    "fill_color":"Pink"
}
